### ISSUE TITLE
Vulnerability Database

### ISSUE THREAD

**Issue by jgarci40** [buptsseGJ/VulSeeker#2]
Do you have a vulnerability database that you can share that has a decent amount of vulnerable binaries?

Thank you for your time and consideration.

Josh

**Comment by buptsseGJ** [comment]
Sorry，we do not have a vulnerability database, which is difficult to collect compiled binary vulnerability samples. Only several experimental samples are contained.

**Comment by jgarci40** [comment]
Thank you for the info.
